import Image from "next/image";
import Link from "next/link";
import { aboutContent } from "@/lib/about";
import { Footer, MobileActionBar } from "./home-sections";

const Arrow = () => <span aria-hidden="true">↗</span>;

export function AboutHero() { const { hero } = aboutContent; return <section className="editorial-hero about-hero"><Image src={hero.image} alt="Warm dining room at The Royal Spice" fill priority sizes="100vw"/><div className="hero-shade"/><div className="editorial-hero-content"><p className="eyebrow light">{hero.eyebrow}</p><h1>{hero.title}</h1><p>{hero.copy}</p></div></section>; }
export function StorySection() { const { story } = aboutContent; return <section className="story-section page-section"><div className="story-image"><Image src={story.image} alt="Guests enjoying the atmosphere at The Royal Spice" fill sizes="(max-width: 760px) 100vw, 50vw"/></div><div className="story-copy"><p className="eyebrow">{story.eyebrow}</p><h2>{story.title}</h2><p>{story.copy}</p><span className="story-detail">{story.detail}</span></div></section>; }
export function JourneyTimeline() { return <section className="journey page-section"><div className="section-heading"><div><p className="eyebrow">A DECADE OF FLAVOUR</p><h2>Our <i>journey.</i></h2></div></div><ol className="journey-list">{aboutContent.journey.map((item) => <li key={item.year}><span>{item.year}</span><strong>{item.title}</strong></li>)}</ol></section>; }
export function ChefSection() { const { chef } = aboutContent; return <section className="chef-section page-section"><div className="chef-images"><div className="chef-portrait"><Image src={chef.portrait} alt="Chef Arjun Mehra in the kitchen" fill sizes="(max-width: 760px) 80vw, 38vw"/></div><div className="chef-kitchen"><Image src={chef.kitchen} alt="Chef preparing traditional Indian dishes" fill sizes="(max-width: 760px) 55vw, 22vw"/></div></div><div className="chef-copy"><p className="eyebrow">{chef.eyebrow}</p><h2>{chef.title}</h2><p>{chef.philosophy}</p><p className="chef-name"><strong>{chef.name}</strong><span>{chef.role}</span></p></div></section>; }
export function ValuesSection() { return <section className="values-section page-section"><div className="section-heading"><div><p className="eyebrow">WHAT GUIDES US</p><h2>Made with <i>meaning.</i></h2></div></div><div className="values-list">{aboutContent.values.map((value, index) => <article key={value.title}><span>0{index + 1}</span><div><h3>{value.title}</h3><p>{value.copy}</p></div></article>)}</div></section>; }
export function AboutCTA() { return <section className="about-cta"><p className="eyebrow">YOUR TABLE AWAITS</p><h2>Come for the food. <i>Stay for the feeling.</i></h2><div><Link className="button button-dark" href="/menu">Explore Menu <Arrow /></Link><Link className="button button-outline-dark" href="/order">Order &amp; Reserve <Arrow /></Link></div></section>; }
export function AboutPageContent() { return <><AboutHero/><StorySection/><JourneyTimeline/><ChefSection/><ValuesSection/><AboutCTA/><Footer/><MobileActionBar/></>; }
