"use client";
import Image from "next/image";
import { useEffect, useState } from "react";
import Link from "next/link";
import { galleryCategories, galleryItems } from "@/lib/gallery";
import { Footer, MobileActionBar } from "./home-sections";

const Arrow = () => <span aria-hidden="true">↗</span>;
export function GalleryHero() { return <section className="editorial-hero gallery-hero"><Image src={galleryItems[4].src} alt="Atmospheric interior of The Royal Spice" fill priority sizes="100vw"/><div className="hero-shade"/><div className="editorial-hero-content"><p className="eyebrow light">THE EXPERIENCE</p><h1>A taste for the <i>eyes, too.</i></h1><p>Step inside The Royal Spice.</p></div></section>; }
export function GalleryLightbox({ item, onClose, onMove }) { useEffect(() => { const handleKey = (event) => { if (event.key === "Escape") onClose(); if (event.key === "ArrowRight") onMove(1); if (event.key === "ArrowLeft") onMove(-1); }; document.addEventListener("keydown", handleKey); return () => document.removeEventListener("keydown", handleKey); }, [onClose, onMove]); return <div className="gallery-lightbox" role="dialog" aria-modal="true" aria-label={item.caption} onClick={onClose}><button className="lightbox-close" onClick={onClose} aria-label="Close image viewer">×</button><button className="lightbox-prev" onClick={(e) => { e.stopPropagation(); onMove(-1); }} aria-label="Previous image">←</button><div className="lightbox-image" onClick={(e) => e.stopPropagation()}><Image src={item.src} alt={item.alt} fill sizes="90vw"/><p>{item.caption}</p></div><button className="lightbox-next" onClick={(e) => { e.stopPropagation(); onMove(1); }} aria-label="Next image">→</button></div>; }
export function GalleryPageContent() { const [active, setActive] = useState("all"); const [selected, setSelected] = useState(null); const filtered = active === "all" ? galleryItems : galleryItems.filter((item) => item.category === active); const move = (direction) => setSelected((current) => { const index = filtered.findIndex((item) => item.src === current?.src); return filtered[(index + direction + filtered.length) % filtered.length]; }); return <><GalleryHero/><main className="gallery-page-content"><nav className="gallery-filters" aria-label="Gallery categories">{galleryCategories.map((category) => <button key={category} className={active === category ? "active" : ""} onClick={() => setActive(category)} aria-pressed={active === category}>{category}</button>)}</nav><section className="gallery-masonry" aria-label="Restaurant gallery">{filtered.map((item, index) => <button key={item.src} className={`gallery-tile gallery-tile-${index % 5}`} onClick={() => setSelected(item)} aria-label={`Open ${item.caption}`}><Image src={item.src} alt={item.alt} fill sizes="(max-width: 760px) 100vw, 50vw"/><span>{item.caption}</span></button>)}</section><section className="instagram-section"><p className="eyebrow">FOLLOW THE MOMENTS</p><h2>More from <i>The Royal Spice.</i></h2><p>Follow us for dishes, people, and moments from the restaurant.</p><Link className="underlined-link" href="#">Follow on Instagram <Arrow /></Link></section></main>{selected && <GalleryLightbox item={selected} onClose={() => setSelected(null)} onMove={move}/>}<Footer/><MobileActionBar/></>; }
